// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/about-me": {
    params: {};
  };
  "/demos": {
    params: {};
  };
  "/test": {
    params: {};
  };
  "/welcome": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/contact" | "/about-me" | "/demos" | "/test" | "/welcome";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "./routes/about-me.tsx": {
    id: "routes/about-me";
    page: "/about-me";
  };
  "./routes/demos.tsx": {
    id: "routes/demos";
    page: "/demos";
  };
  "./routes/test.ts": {
    id: "routes/test";
    page: "/test";
  };
  "./welcome/welcome.tsx": {
    id: "welcome/welcome";
    page: "/welcome";
  };
};